var a =$("#id");
$("#a").on('click',function(){
    a.text("Hypertext Markup Language (HTML) is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages.HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.HTML elements are the building blocks of HTML pages.With HTML constructs, images and other objects such as interactive forms may be embedded into the rendered page.HTML provides a means to create structured documents by denoting structural semantics for text such as headings, paragraphs, lists, links, quotes and other items.HTML elements are delineated by tags, written using angle brackets.Tags such as <img /> and < input /> directly introduce content into the page.Other tags such as <p> surround and provide information about document text and may include other tags as sub - elements.Browsers do not display the HTML tags, but use them to interpret the content of the page.HTML can embed programs written in a scripting language such as JavaScript, which affects the behavior and content of web pages.Inclusion of CSS defines the look and layout of content.The World Wide Web Consortium(W3C), former maintainer of the HTML and current maintainer of the CSS standards, has encouraged the use of CSS over explicit presentational HTML since 1997.");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#b").on('click', function () {
    a.text("Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language like HTML.[1] CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.[2]CSS is designed to enable the separation of presentation and content, including layout, colors, and fonts.[3] This separation can improve content accessibility, provide more flexibility and control in the specification of presentation characteristics, enable multiple web pages to share formatting by specifying the relevant CSS in a separate.css file, and reduce complexity and repetition in the structural content.Separation of formatting and content also makes it feasible to present the same markup page in different styles for different rendering methods, such as on - screen, in print, by voice(via speech - based browser or screen reader), and on Braille - based tactile devices.CSS also has rules for alternate formatting if the content is accessed on a mobile device.[4]The name cascading comes from the specified priority scheme to determine which style rule applies if more than one rule matches a particular element.This cascading priority scheme is predictable.The CSS specifications are maintained by the World Wide Web Consortium(W3C).Internet media type(MIME type) text / css is registered for use with CSS by RFC 2318(March 1998).The W3C operates a free CSS validation service for CSS documents.[5]In addition to HTML, other markup languages support the use of CSS including XHTML, plain XML, SVG, and XUL.");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#c").on('click', function () {
    a.text("Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains CSS- and (optionally) JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components.Bootstrap is the sixth - most - starred project on GitHub, with more than 135, 000 stars, behind freeCodeCamp(almost 307, 000 stars) and marginally behind Vue.js framework.[2] According to Alexa Rank, Bootstrap is in the top - 2000 in US while vuejs.org is in top - 7000 in US.[3]");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#d").on('click', function () {
    a.text("PHP is a popular general-purpose scripting language that is especially suited to web development[5]. It was originally created by Rasmus Lerdorf in 1994;[6] the PHP reference implementation is now produced by The PHP Group.[7] PHP originally stood for Personal Home Page,[6] but it now stands for the recursive initialism PHP: Hypertext Preprocessor.[8]PHP code is usually processed on a web server by a PHP interpreter implemented as a module, a daemon or as a Common Gateway Interface(CGI) executable.On a web server, the result of the interpreted and executed PHP code – which may be any type of data, such as generated HTML or binary image data – would form the whole or part of a HTTP response.Various web template systems, web content management systems, and web frameworks exist which can be employed to orchestrate or facilitate the generation of that response.Additionally, PHP can be used for many programming tasks outside of the web context, such as standalone graphical applications[9] and robotic drone control.[10] Arbitrary PHP code can also be interpreted and executed via command line interface(CLI).The standard PHP interpreter, powered by the Zend Engine, is free software released under the PHP License.PHP has been widely ported and can be deployed on most web servers on almost every operating system and platform, free of charge.[11]The PHP language evolved without a written formal specification or standard until 2014, with the original implementation acting as the de facto standard which other implementations aimed to follow.Since 2014, work has gone on to create a formal PHP specification.[12]As of April 2020, over half of sites on the web using PHP are still on discontinued / 'EOLed'[13] version 5.6 or older;[14] and with version 7.0 and 7.1 over 68 %, that are neither officially supported by The PHP Development Team, [15] while security support is provided by third parties, such as Debian (up to June 2020 for PHP 5).[16] Because of the popularity of PHP that means at least 53 % of the websites in the world run on implementations of languages no longer supported by their designers.In addition, PHP version 7.2, the most popular supported PHP version, will stop getting security updates on November 30, 2020.[13]");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#e").on('click', function () {
    a.text("MySQL (/ˌmaɪˌɛsˌkjuːˈɛl/ 'My S - Q - L')[5] is an open-source relational database management system (RDBMS).[5][6] Its name is a combination of 'My', the name of co-founder Michael Widenius's daughter,[7] and 'SQL', the abbreviation for Structured Query Language.MySQL is free and open - source software under the terms of the GNU General Public License, and is also available under a variety of proprietary licenses.MySQL was owned and sponsored by the Swedish company MySQL AB, which was bought by Sun Microsystems(now Oracle Corporation).[8] In 2010, when Oracle acquired Sun, Widenius forked the open - source MySQL project to create MariaDB.[9]MySQL is a component of the LAMP web application software stack(and others), which is an acronym for Linux, Apache, MySQL, Perl / PHP / Python.MySQL is used by many database - driven web applications, including Drupal, Joomla, phpBB, and WordPress.MySQL is also used by many popular websites, including Facebook, [10][11] Flickr, [12] MediaWiki, [13] Twitter, [14] and YouTube.[15]");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#f").on('click', function () {
    a.text("JavaScript (/ˈdʒɑːvəˌskrɪpt/),[6] often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.[7] JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.Alongside HTML and CSS, JavaScript is one of the core technologies of the World Wide Web.[8] JavaScript enables interactive web pages and is an essential part of web applications.The vast majority of websites use it for client - side page behavior, [9] and all major web browsers have a dedicated JavaScript engine to execute it.As a multi - paradigm language, JavaScript supports event - driven, functional, and imperative programming styles.It has application programming interfaces(APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model(DOM).However, the language itself does not include any input / output(I / O), such as networking, storage, or graphics facilities, as the host environment(usually a web browser) provides those APIs.JavaScript engines were originally used only in web browsers, but they are now embedded in some servers, usually via Node.js.They are also embedded in a variety of applications created with frameworks such as Electron and Cordova.Although there are similarities between JavaScript and Java, including language name, syntax, and respective standard libraries, the two languages are distinct and differ greatly in design.");
    a.removeClass("id1");
    a.addClass("id2");
});

$("#g").on('click', function () {
    a.text("jQuery is a JavaScript library designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animation, and Ajax.[2] It is free, open-source software using the permissive MIT License.[3] As of May 2019, jQuery is used by 73% of the 10 million most popular websites.[4] Web analysis indicates that it is the most widely deployed JavaScript library by a large margin, having 3 to 4 times more usage than any other JavaScript library.[4][5]jQuery's syntax is designed to make it easier to navigate a document, select DOM elements, create animations, handle events, and develop Ajax applications. jQuery also provides capabilities for developers to create plug-ins on top of the JavaScript library. This enables developers to create abstractions for low-level interaction and animation, advanced effects and high-level, themeable widgets. The modular approach to the jQuery library allows the creation of powerful dynamic web pages and Web applications.The set of jQuery core features—DOM element selections, traversal and manipulation—enabled by its selector engine(named 'Sizzle' from v1.3), created a new 'programming style', fusing algorithms and DOM data structures.This style influenced the architecture of other JavaScript frameworks like YUI v3 and Dojo, later stimulating the creation of the standard Selectors API.[6] Later, this style has been enhanced with a deeper algorithm - data fusion in an heir of jQuery, the D3.js framework.Microsoft and Nokia bundle jQuery on their platforms.[7] Microsoft includes it with Visual Studio[8] for use within Microsoft's ASP.NET AJAX and ASP.NET MVC frameworks while Nokia has integrated it into the Web Run-Time widget development platform.[9]");
    a.removeClass("id1");
    a.addClass("id2");
});